# Generated by Django 4.1.1 on 2022-09-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='car',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='mobile',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='song',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
