# Generated by Django 4.1.1 on 2022-09-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_alter_question_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app1.question"
            ),
        ),
    ]
