# Generated by Django 4.1.1 on 2022-09-22 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="mobile",
            field=models.CharField(
                max_length=13,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Phone number must be entered in the format: "+999999999". Up to 14 digits allowed.',
                        regex="^\\+[1-9]\\d{1,14}$",
                    )
                ],
            ),
        ),
    ]
